### ISSUE TITLE
Incorrect channel calculation

### ISSUE THREAD

**Issue by OrdinaryMagician** [tmiasko/fsb-vorbis-extractor#4]
I noticed this while extracting files that have more than 2 channels (8-channel ambiences from Dark Souls games, specifically). The thing is, I found out that bits 5 AND 6 are used to represent the channel count as the exponent of a power of two.

In line 103 of container.cpp, you should use something like `1u << ((mode & 96u) >> 5u)`, I guess.

This is true at least for Dark Souls 3. So I may be wrong.

**Comment by tmiasko** [comment]
As far as I can remember, the bit 6 used to be always zero in samples I used for testing, so this would be backward compatible change. 

Great find, thanks @OrdinaryMagician!
