### ISSUE TITLE
Can't extract headerless OGG files

### ISSUE THREAD

**Issue by GilrainB** [tmiasko/fsb-vorbis-extractor#5]
When I try to extract or list files of an fsb with just 1 vorbis file and no header on this vorbis, this error occurs:
```
F0205 14:18:37.337327    30 container.cpp:162] Check failed: false Unexpected extra header type:
*** Check failure stack trace: ***
    @     0x7fb0541db5cd  google::LogMessage::Fail()
    @     0x7fb0541dd433  google::LogMessage::SendToLog()
    @     0x7fb0541db15b  google::LogMessage::Flush()
    @     0x7fb0541dde1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x4112be  fsb::container::read_sample_header()
    @           0x4118c4  fsb::container::read_sample_headers()
    @           0x412663  fsb::container::container()
    @           0x40ed2b  main
    @     0x7fb053000830  __libc_start_main
    @           0x410369  _start
    @              (nil)  (unknown)
```

Before I used this tool I also tried to extract the ogg with Aezay FSB Extractor 16.10.21
Aezay FSB Extractor stated it thew it was a vorbis, 44100Hz, stereo, bitrate and duration.
It also noted "The extracted Celt/Ogg sample will not have a header, and cannot be played".
The exported file would then be a headerless ogg file.

[Menu_music__Part1.zip](https://github.com/tmiasko/fsb-vorbis-extractor/files/1695252/Menu_music__Part1.zip)

Is that header maybe fixable by this tool/could this tool generate one?

**Comment by tmiasko** [comment]
You could try to ignore extra headers, maybe they aren't particularly
important. See for example this commit (which isn't in this repository):
https://github.com/SamusAranX/fsb-vorbis-extractor/commit/17275f152178e9569190974576d0665f5f0aecf7

The general intention of this tool is to produce correct Ogg Vorbis files that
can be played.  Of course, it probably supports only some subset of FSB files
that I happened to use during development.
